import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home1.module.css";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cudo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"
        ></link>
      </Head>

      <div className={styles.panel1}>
        <dev className={styles.busca}>
          <a>
            <i class="fa fa-times-circle"></i>
          </a>
          <a>
            <i class="fa fa-store-alt"></i>
          </a>
          <a>
            <i class="fa fa-times-circle"></i>
          </a>
        </dev>

        <dev className={styles.logo}>
          <h1 className={styles.title1}>
            CU<a>DO</a>
          </h1>
        </dev>

        <dev className={styles.busca}>
          <a>m</a>
        </dev>
      </div>

      <div className={styles.panel2}></div>
    </div>
  );
}
