import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function registrar() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cudo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.content}>
        <main className={styles.main}>
          <img
            className={styles.img}
            src="/undraw_Loading_re_5axr.png"
            alt="logo"
          />
          <h1>Iniciar Registro</h1>
          <dev className={styles.panel1}>
            <input
              className={styles.input}
              type="text"
              placeholder="Nombre"
            ></input>
            <input
              className={styles.input}
              type="text"
              placeholder="Apellido"
            ></input>
            <input
              className={styles.input}
              type="text"
              placeholder="Correo"
            ></input>
            <input
              className={styles.input}
              type="password"
              placeholder="Contraseña"
            ></input>
          </dev>
          <button className={styles.boton}>Registrar</button>
          <p className={styles.title}>
            Y tienes una cuenta,
            <a href="http://localhost:3000"> inicia sesion.</a>
          </p>
        </main>
      </div>
    </div>
  );
}
